[project]
name = 'Animal-Adoption-Dapp'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Animal-Adoption-Dapp]
path = 'contracts/Animal-Adoption-Dapp.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
